In [132]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [133]:
df = pd.read_csv('uci-secom.csv')
df = df.iloc[:, 1:]
df.head()

,0,1,2,3,4,5,6,7,8,9,...,581,582,583,584,585,586,587,588,589,Pass/Fail
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,0.0162,...,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN,-1
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,-0.0005,...,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045,-1
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,0.0041,...,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602,1
3,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,-0.0124,...,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432,-1
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,-0.0031,...,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432,-1

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1567 entries, 0 to 1566
Columns: 591 entries, 0 to Pass/Fail
dtypes: float64(590), int64(1)
memory usage: 7.1 MB

In [135]:
df.isnull().sum()

0             6
1             7
2            14
3            14
4            14
             ..
586           1
587           1
588           1
589           1
Pass/Fail     0
Length: 591, dtype: int64

In [136]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,581,582,583,584,585,586,587,588,589,Pass/Fail
count,1561.000000,1560.000000,1553.000000,1553.000000,1553.000000,1553.0,1553.000000,1558.000000,1565.000000,1565.000000,...,618.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1567.000000
mean,3014.452896,2495.850231,2200.547318,1396.376627,4.197013,100.0,101.112908,0.121822,1.462862,-0.000841,...,97.934373,0.500096,0.015318,0.003847,3.067826,0.021458,0.016475,0.005283,99.670066,-0.867262
std,73.621787,80.407705,29.513152,441.691640,56.355540,0.0,6.237214,0.008961,0.073897,0.015116,...,87.520966,0.003404,0.017180,0.003720,3.578033,0.012358,0.008808,0.002867,93.891919,0.498010
min,2743.240000,2158.750000,2060.660000,0.000000,0.681500,100.0,82.131100,0.000000,1.191000,-0.053400,...,0.000000,0.477800,0.006000,0.001700,1.197500,-0.016900,0.003200,0.001000,0.000000,-1.000000
25%,2966.260000,2452.247500,2181.044400,1081.875800,1.017700,100.0,97.920000,0.121100,1.411200,-0.010800,...,46.184900,0.497900,0.011600,0.003100,2.306500,0.013425,0.010600,0.003300,44.368600,-1.000000
50%,3011.490000,2499.405000,2201.066700,1285.214400,1.316800,100.0,101.512200,0.122400,1.461600,-0.001300,...,72.288900,0.500200,0.013800,0.003600,2.757650,0.020500,0.014800,0.004600,71.900500,-1.000000
75%,3056.650000,2538.822500,2218.055500,1591.223500,1.525700,100.0,104.586700,0.123800,1.516900,0.008400,...,116.539150,0.502375,0.016500,0.004100,3.295175,0.027600,0.020300,0.006400,114.749700,-1.000000
max,3356.350000,2846.440000,2315.266700,3715.041700,1114.536600,100.0,129.252200,0.128600,1.656400,0.074900,...,737.304800,0.509800,0.476600,0.104500,99.303200,0.102800,0.079900,0.028600,737.304800,1.000000

In [137]:
len(df)

1567

In [138]:
# 결측치 최빈값으로 채우기

df.fillna(df.mean(), inplace=True)

In [141]:
df['5'].value_counts()

5
100.0    1567
Name: count, dtype: int64

In [142]:
df['378'].value_counts()

378
0.0    1567
Name: count, dtype: int64

In [147]:
# 

col_lst = list(df.columns)
drop_col = []
for col in col_lst:
	if len(df[col].value_counts()) == 1:
		drop_col.append(col)
len(drop_col)

116

In [149]:
df.drop(columns=drop_col)

,0,1,2,3,4,6,7,8,9,10,...,581,582,583,584,585,586,587,588,589,Pass/Fail
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,97.6133,0.1242,1.500500,0.016200,-0.003400,...,97.934373,0.5005,0.0118,0.0035,2.3630,0.021458,0.016475,0.005283,99.670066,-1
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,102.3433,0.1247,1.496600,-0.000500,-0.014800,...,208.204500,0.5019,0.0223,0.0055,4.4447,0.009600,0.020100,0.006000,208.204500,-1
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,95.4878,0.1241,1.443600,0.004100,0.001300,...,82.860200,0.4958,0.0157,0.0039,3.1745,0.058400,0.048400,0.014800,82.860200,1
3,2988.72,2479.90,2199.0333,909.7926,1.3204,104.2367,0.1217,1.488200,-0.012400,-0.003300,...,73.843200,0.4990,0.0103,0.0025,2.0544,0.020200,0.014900,0.004400,73.843200,-1
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.3967,0.1235,1.503100,-0.003100,-0.007200,...,97.934373,0.4800,0.4766,0.1045,99.3032,0.020200,0.014900,0.004400,73.843200,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,2899.41,2464.36,2179.7333,3085.3781,1.4843,82.2467,0.1248,1.342400,-0.004500,-0.005700,...,203.172000,0.4988,0.0143,0.0039,2.8669,0.006800,0.013800,0.004700,203.172000,-1
1563,3052.31,2522.55,2198.5667,1124.6595,0.8763,98.4689,0.1205,1.433300,-0.006100,-0.009300,...,97.934373,0.4975,0.0131,0.0036,2.6238,0.006800,0.013800,0.004700,203.172000,-1
1564,2978.81,2379.78,2206.3000,1110.4967,0.8236,99.4122,0.1208,1.462862,-0.000841,0.000146,...,43.523100,0.4987,0.0153,0.0041,3.0590,0.019700,0.008600,0.002500,43.523100,-1
1565,2894.92,2532.01,2177.0333,1183.7287,1.5726,98.7978,0.1213,1.462200,-0.007200,0.003200,...,93.494100,0.5004,0.0178,0.0038,3.5662,0.026200,0.024500,0.007500,93.494100,-1
1566,2944.92,2450.76,2195.4444,2914.1792,1.5978,85.1011,0.1235,1.462862,-0.000841,0.000146,...,137.784400,0.4987,0.0181,0.0040,3.6275,0.011700,0.016200,0.004500,137.784400,-1

In [150]:
def metrics(model, y_tst, pred):
		acc = accuracy_score(y_tst, pred)
		precision = precision_score(y_tst, pred)
		recall = recall_score(y_tst, pred)
		f1 = f1_score(y_tst, pred)
		
		return f'{model} Accuracy : {round(acc, 4)}, Precision : {round(precision, 4)}, Recall : {round(recall, 4)}, F1 Score : {round(f1, 4)}'

In [151]:
def model_predict(model_lst, x_trn, x_tst, y_trn, y_tst):
		
	for model in model_lst:
		model.fit(x_trn, y_trn)
		pred = model.predict(x_tst)
		result = metrics(model, y_tst, pred)
		print(result)

In [152]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from lightgbm import LGBMClassifier
import warnings
warnings.filterwarnings('ignore')

## Validation

In [153]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [154]:
x_trn, x_val, y_trn, y_val = train_test_split(x, y, test_size=0.2, random_state=0)

rf_cl = RandomForestClassifier()
dtree = DecisionTreeClassifier()
logistic = LogisticRegression()
lgbm = LGBMClassifier()
xgb = XGBClassifier()

model_lst = [rf_cl, dtree, logistic, lgbm] #xgb
model_predict(model_lst, x_trn, x_val, y_trn, y_val)

RandomForestClassifier() Accuracy : 0.9586, Precision : 0.0, Recall : 0.0, F1 Score : 0.0
DecisionTreeClassifier() Accuracy : 0.8981, Precision : 0.087, Recall : 0.1538, F1 Score : 0.1111
LogisticRegression() Accuracy : 0.9522, Precision : 0.0, Recall : 0.0, F1 Score : 0.0
[LightGBM] [Info] Number of positive: 91, number of negative: 1162
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005496 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 103317
[LightGBM] [Info] Number of data points in the train set: 1253, number of used features: 464
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.072626 -> initscore=-2.547038
[LightGBM] [Info] Start training from score -2.547038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LGBMClassifier() Accuracy : 0.9586, Precision : 0.0, Recall : 0.0, F1 Score : 0.0

## GridSearchCV

In [156]:
from sklearn.model_selection import GridSearchCV

def grid_search(model, params, scores, x_train, y_train):
	for score in scores:
		grid_cv = GridSearchCV(model, param_grid=params, scoring=score, cv=5)
		grid_cv.fit(x_train , y_train)
		print('GridSearchCV 최고 {0} 정확도 수치:{1:.4f}'.format(score, grid_cv.best_score_))
		print('GridSearchCV 최적 하이퍼 파라미터:', grid_cv.best_params_)

### Random Forest

In [158]:
params = {
	'n_estimators' : [100, 300],
    'max_depth' : [5, 10, 16 ,20],
	'max_leaf_nodes' : [15, 20]
	}

scores = ['accuracy', 'precision', ] # 'recall', 'f1', 'roc_auc'

grid_search(rf_cl, params, scores, x, y)

GridSearchCV 최고 accuracy 정확도 수치:0.9336
GridSearchCV 최적 하이퍼 파라미터: {'max_depth': 5, 'max_leaf_nodes': 15, 'n_estimators': 100}
GridSearchCV 최고 precision 정확도 수치:0.0667
GridSearchCV 최적 하이퍼 파라미터: {'max_depth': 10, 'max_leaf_nodes': 20, 'n_estimators': 100}

## Test

In [ ]:
x_trn, x_val, y_trn, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=0)

rf_cl = RandomForestClassifier()
dtree = DecisionTreeClassifier()
logistic = LogisticRegression()
lgbm = LGBMClassifier()
xgb = XGBClassifier()

model_lst = [rf_cl, dtree, logistic, lgbm] #xgb
model_predict(model_lst, x_trn, x_val, y_trn, y_val)

RandomForestClassifier() Accuracy : 0.678, Precision : 0.7735, Recall : 0.6553, F1 Score : 0.7095
DecisionTreeClassifier() Accuracy : 0.6356, Precision : 0.6922, Recall : 0.7071, F1 Score : 0.6996
LogisticRegression() Accuracy : 0.6379, Precision : 0.6924, Recall : 0.7134, F1 Score : 0.7027
[LightGBM] [Info] Number of positive: 3145, number of negative: 2133
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000269 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 573
[LightGBM] [Info] Number of data points in the train set: 5278, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.595870 -> initscore=0.388284
[LightGBM] [Info] Start training from score 0.388284
LGBMClassifier() Accuracy : 0.6621, Precision : 0.75, Recall : 0.6553, F1 Score : 0.6995

In [ ]:
rf_cl = RandomForestClassifier()
model_lst = [rf_cl]
model_predict(model_lst, x_train, x_test, y_train, y_test)

RandomForestClassifier() Accuracy : 0.666, Precision : 0.7809, Recall : 0.612, F1 Score : 0.6862

In [ ]:
# GridSearchCV 최적 하이퍼 파라미터: {'max_depth': 10, 'max_leaf_nodes': 10, 'n_estimators': 300}
rf_cl = RandomForestClassifier(max_depth=15, max_leaf_nodes=10, n_estimators=50)
model_lst = [rf_cl]
model_predict(model_lst, x_train, x_test, y_train, y_test)

RandomForestClassifier(max_depth=15, max_leaf_nodes=10, n_estimators=50) Accuracy : 0.6778, Precision : 0.9021, Recall : 0.516, F1 Score : 0.6565

In [ ]:
rf_cl = RandomForestClassifier(max_depth=10, max_leaf_nodes=10, n_estimators=100)
model_lst = [rf_cl]
model_predict(model_lst, x_train, x_test, y_train, y_test)

RandomForestClassifier(max_depth=10, max_leaf_nodes=10) Accuracy : 0.6723, Precision : 0.8503, Recall : 0.5472, F1 Score : 0.6659

In [ ]:
rf_cl = RandomForestClassifier(max_depth=25, max_leaf_nodes=20, n_estimators=100)
model_lst = [rf_cl]
model_predict(model_lst, x_train, x_test, y_train, y_test)

RandomForestClassifier(max_depth=25, max_leaf_nodes=20) Accuracy : 0.678, Precision : 0.8843, Recall : 0.5297, F1 Score : 0.6625